# Generated by Django 2.2 on 2021-02-18 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_dojo_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dojo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
